excluded:
  - Pods
  - vendor

disabled_rules:
  - contrasted_opening_brace
  - explicit_type_interface
  - file_header
  - file_name
  - explicit_acl
  - explicit_top_level_acl
  - nslocalizedstring_require_bundle
  - prohibited_interface_builder
  - class_delegate_protocol
  - one_declaration_per_file
  - no_magic_numbers
  - trailing_closure
  - required_deinit
  - explicit_enum_raw_value
  - file_types_order
  - sorted_enum_cases
  - identifier_name
  - nslocalizedstring_key
  - override_in_extension
  - implicit_return
  - indentation_width
  - fallthrough
  - no_fallthrough_only
  - object_literal
  - blanket_disable_command
  - switch_case_on_newline
  - todo

opt_in_rules:
  - all

analyzer_rules:
  - all

line_length:
  warning: 160

file_length:
  warning: 500

trailing_comma:
  mandatory_comma: true

type_contents_order:
  order: [[case], [type_alias, associated_type], [subtype], [type_property], [instance_property], [ib_inspectable], [ib_outlet], [initializer], [type_method], [view_life_cycle_method], [deinitializer], [other_method], [ib_action, ib_segue_action], [subscript]]
