excluded:
  - Pods
  - vendor
  - JumpKit/External
  - JumpKit/JumpDesignSystem/Core/DSConstants/DSConstantConfigurations.swift
  - JumpKit/SDK/Generated

disabled_rules:
  - contrasted_opening_brace
  - explicit_type_interface
  - file_header
  - file_name
  - explicit_acl
  - explicit_top_level_acl
  - nslocalizedstring_require_bundle
  - prohibited_interface_builder
  - class_delegate_protocol
  - one_declaration_per_file
  - no_magic_numbers
  - trailing_closure
  - required_deinit

opt_in_rules:
  - all

analyzer_rules:
  - all

# Custom rule parameters

line_length:
  warning: 160
  # ignores_function_declarations: false
  # ignores_comments: true
  # ignores_interpolated_strings: true
  # ignores_urls: true

file_length:
  warning: 500
